name: Action training demo

on:
  workflow_call:
    inputs: 
      environment:
        description: 'The environment to deploy to'
        required: true
        type: string
      app-name:
        description: 'The name of the app to deploy'
        required: false
        type: string
      package-path:
        description: 'The path to the package to deploy'
        required: true
        type: string
   

jobs:
  deploy:

    runs-on: ubuntu-latest
    env:
      AZURE_APP_NAME: ${{ vars.APP_NAME }}

    environment: 
      name: ${{ inputs.environment }}

    steps:
      
      - name: Echo environment vars
        run: |
         echo "app name  ${{ vars.APP_NAME }}"
         echo "env ${{ inputs.environment }}"
     
      - name: Download from artifacts
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.package-path }}
          path: ${{ inputs.package-path }}


      - name: Azure Web App Deploy
        uses: azure/webapps-deploy@v2
        with:
          slot-name: ${{ vars.SLOT_NAME }}
          app-name: ${{ env.AZURE_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ${{ inputs.package-path }}




